stages:
  - build
  - test
  - release

image: registry.forge.hefr.ch/frederic.bapst/intelli-prolog-2/preconfigured-gradle:7.3-jdk11

build:
  stage: build
  script:
    # Init the parser and lexer
    - gradle generateParser
    - gradle generateLexer
    # Build the project
    - gradle build
    - gradle buildPlugin
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 hour

test:
  stage: test
  script:
    # Init the parser and lexer
    - gradle generateParser
    - gradle generateLexer
    # Run the tests
    - gradle test
  artifacts:
    paths:
      - build/reports/tests/test
    expire_in: 1 hour

release:
  variables:
    ZIP: https://gitlab.forge.hefr.ch/frederic.bapst/intelli-prolog-2/-/jobs/$CI_JOB_ID/artifacts/raw/build/distributions
  stage: release
  script:
    # Init the parser and lexer
    - gradle generateParser
    - gradle generateLexer
    # Build the project
    - gradle build
    - gradle buildPlugin
  after_script:
    - export VERSION=`cat gradle.properties | grep "pluginVersion" | cut -d '=' -f2`
    - export ZIP_FILE=$ZIP/IntelliProlog-$VERSION.zip
  only:
    - master
    - tags
  artifacts:
    paths:
      - build/distributions/*.zip
    expire_in: never

  release:
    name: 'Release $VERSION'
    description: 'Ceci est la version "$VERSION" du plugin Intelli-Prolog'
    tag_name: '$VERSION'
    ref: '$COMMIT_REF'
    assets:
      links:
        - name: 'ZIP file'
          url: $ZIP_FILE
