stages:
  - build
  - test

image: registry.forge.hefr.ch/frederic.bapst/intelli-prolog-2/preconfigured-gradle:7.3-jdk11

build:
    stage: build
    script:
        # Init the parser and lexer
        - gradle generateParser
        - gradle generateLexer
        # Build the project
        - gradle build
        - gradle buildPlugin
    artifacts:
        paths:
          - build/libs/*.jar
        expire_in: 1 hour

test:
    stage: test
    script:
      # Init the parser and lexer
      - gradle generateParser
      - gradle generateLexer
      # Run the tests
      - gradle test
    artifacts:
        paths:
          - build/reports/tests/test
        expire_in: 1 hour

