package ch.eif.intelliprolog.ui;

import ch.eif.intelliprolog.PrologSettingsEditor;
import com.intellij.openapi.fileEditor.FileEditorManager;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.IOException;

public class PrologSettingsEditorForm {
    private JLabel sourceFileLabel;
    private JTextField sourceFileField;
    private JButton sourceFileBrowseBtn;
    private JCheckBox traceCheckBox;
    private JLabel initialGoalLabel;
    private JTextField initialGoalField;
    private JPanel panel;

    private String canonicalPath;
    private File selectedFile;


    public PrologSettingsEditorForm(final PrologSettingsEditor.Mediator mediator) {

        mediator.form = this;

        FileEditorManager fileEditorManager = FileEditorManager.getInstance(mediator.project);
        canonicalPath = fileEditorManager.getOpenFiles()[0].getCanonicalPath();

        $$$setupUI$$$();

        sourceFileField.setText(canonicalPath);

        sourceFileBrowseBtn.addActionListener(e -> {
            JFileChooser fileChooser = new JFileChooser(canonicalPath);
            int returnVal = fileChooser.showOpenDialog(this.panel);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                selectedFile = fileChooser.getSelectedFile();
                try {
                    canonicalPath = selectedFile.getCanonicalPath();
                } catch (IOException e1) {
                    e1.printStackTrace();
                }
            }
        });
    }

    public JPanel getPanel() {
        return panel;
    }

    public File getSelectedFile() {
        return selectedFile;
    }

    public boolean getTraceCheckBox() {
        return traceCheckBox.isSelected();
    }

    public String getInitialGoalField() {
        return initialGoalField.getText();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(3, 3, new Insets(0, 0, 0, 0), -1, -1));
        sourceFileLabel = new JLabel();
        sourceFileLabel.setText("Source File");
        panel.add(sourceFileLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        sourceFileField = new JTextField();
        panel.add(sourceFileField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        sourceFileBrowseBtn = new JButton();
        sourceFileBrowseBtn.setText("...");
        panel.add(sourceFileBrowseBtn, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        traceCheckBox = new JCheckBox();
        traceCheckBox.setSelected(false);
        traceCheckBox.setText("Run with trace?");
        panel.add(traceCheckBox, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        initialGoalLabel = new JLabel();
        initialGoalLabel.setText("Initial Goal to run");
        panel.add(initialGoalLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        initialGoalField = new JTextField();
        panel.add(initialGoalField, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        sourceFileLabel.setLabelFor(sourceFileField);
        initialGoalLabel.setLabelFor(initialGoalField);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
